apiVersion: spring.io/v1
kind: ServiceBinding
metadata:
  name: prometheus
spec:
  env:
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    values:
    - info
    - health
    - prometheus
    - metrics
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
