apiVersion: spring.io/v1
kind: ServiceBinding
metadata:
  name: kafka
spec:
  env:
  - name: SPRING_CONFIG_LOCATION
    values:
    - classpath:/
    - file:///etc/config/
  - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_COMPONENTS
    value: always
  template:
    spec:
      imagePullPolicy: Always
      initContainers:
      - name: env
        image: dsyer/spring-boot-bindings
        args: ["-f", "/etc/config/application.properties", "/config/bindings"]
        volumeMounts:
        - name: config
          mountPath: /etc/config
        - name: kafka-metadata
          mountPath: /config/bindings/kafka/metadata
        - name: kafka-secret
          mountPath: /config/bindings/kafka/secret
        - name: kafka-metadata
          mountPath: /config/templates/kafka
      containers:
      - name: app
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: kafka-metadata
        configMap:
          name: kafka-metadata
      - name: kafka-secret
        secret:
          secretName: kafka-secret
      - name: config
        emptyDir: {}


