apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      redis: redis
  template:
    metadata:
      labels:
        redis: redis
    spec:
      containers:
        - image: redis
          name: redis
          ports:
            - containerPort: 6379
              name: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    redis: redis
spec:
  ports:
    - port: 6379
  selector:
    redis: redis