apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- operator.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
- crds/spring.io_springservices_crd.yaml
- crds/spring.io_v1alpha1_springservice_cr.yaml
