apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spring-boot-operator
  template:
    metadata:
      labels:
        name: spring-boot-operator
    spec:
      serviceAccountName: spring-boot-operator
      containers:
        - name: spring-boot-operator
          # Replace this with the built image name
          image: dsyer/spring-boot-operator
          command:
          - spring-boot-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "spring-boot-operator"
