
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: springapplications.spring.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.image
    description: image label
    name: Image
    type: string
  - JSONPath: .status.running
    description: deployment status
    name: Running
    type: boolean
  group: spring.io
  names:
    kind: SpringApplication
    listKind: SpringApplicationList
    plural: springapplications
    singular: springapplication
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SpringApplication is the Schema for the springs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SpringApplicationSpec defines the desired state of SpringApplication
          properties:
            image:
              type: string
          type: object
        status:
          description: SpringApplicationStatus defines the observed state of SpringApplication
          properties:
            label:
              type: string
            running:
              type: boolean
            serviceName:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
